version: '2.2'
services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - COMPOSE_PROJECT_NAME=es
      - CERTS_DIR=/usr/share/elasticsearch/config/certificates
      - ELASTIC_PASSWORD=hogehoge
    command: >
      bash -c '
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs;
        fi;
        chown -R 1000:0 /certs
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes:
      - ./certs:/certs
      - .:/usr/share/elasticsearch/config/certificates
